spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog.xml
#  profiles:
#    active: local

server:
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: NEVER
    include-exception: false

springdoc:
  swagger-ui:
    urlsPrimaryName: wallet
  api-docs:
    path: /openapi/wallets-doc