server:
  port: 9082
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: ALWAYS
    include-exception: true
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
    registerWithEureka: true
    fetchRegistry: true
