spring:
  application:
    name: @project.name@
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog.xml
  profiles:
    active: local

server:
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: NEVER
    include-exception: false

springdoc:
  swagger-ui:
    urlsPrimaryName: wallet
  api-docs:
    path: /openapi/wallets-doc

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
    registerWithEureka: true
  fetchRegistry: ture
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
endpoints:
  shutdown:
    enabled: true